version: 2
sphinx:
  configuration: docs/conf.py
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
      - echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
conda:
  environment: docs/readthedocs-conda-environment.yml
